name: chrono-compositor
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.4
  - pip:
      - -r requirements.txt
      - git+https://github.com/facebookresearch/sam2.git
